<?php
require_once __DIR__ . "/../includes/admin-check.php"; require_once __DIR__ . "/../Config/db.php"; require_once __DIR__ . "/../includes/ui.php";
$total=sr_count($conn,"SELECT COUNT(*) total FROM reports"); $pending=sr_count($conn,"SELECT COUNT(*) total FROM reports WHERE status='Pending'"); $critical=sr_count($conn,"SELECT COUNT(*) total FROM reports WHERE severity IN ('High','Critical') OR priority_score>=75"); $sent=sr_count($conn,"SELECT COUNT(*) total FROM reports WHERE status='Ambulance Sent'"); $available=sr_count($conn,"SELECT COUNT(*) total FROM ambulance_locations WHERE status='available'"); $onway=sr_count($conn,"SELECT COUNT(*) total FROM ambulance_locations WHERE status='on_the_way'"); $resolved=sr_count($conn,"SELECT COUNT(*) total FROM reports WHERE status='Resolved'"); $ai=sr_count($conn,"SELECT COUNT(*) total FROM reports WHERE ai_verdict<>'Not Checked'");
$recent=$conn->query("SELECT r.*, a.ambulance_name FROM reports r LEFT JOIN ambulance_locations a ON a.id=r.assigned_ambulance_id ORDER BY FIELD(r.status,'Pending','Verified','Ambulance Sent','Resolved','Rejected'), r.priority_score DESC, r.created_at DESC LIMIT 8");
$logs=$conn->query("SELECT l.*, r.title, a.ambulance_name FROM response_logs l LEFT JOIN reports r ON r.id=l.report_id LEFT JOIN ambulance_locations a ON a.id=l.ambulance_id ORDER BY l.created_at DESC LIMIT 8");
sr_page_start('Emergency Command Center','dashboard');
?>
<div class="hero-card"><span class="demo-chip">Admin side</span><h2>Live Emergency Command Center</h2><p>Verify accident reports, run AI-assisted triage, dispatch the nearest ambulance and monitor the full response timeline from one dashboard.</p><div class="toolbar" style="margin-top:18px"><a class="btn danger" href="admin-reports.php">🚨 Manage Incidents</a><a class="btn light" href="map.php">🗺 Open Live Map</a><a class="btn light" href="analytics.php">📊 Hotspots</a></div></div>
<div class="grid grid-4" style="margin-top:18px"><div class="card stat"><div class="num"><?php echo $total; ?></div><div class="label">Total Reports</div></div><div class="card stat danger"><div class="num"><?php echo $critical; ?></div><div class="label">High Priority</div></div><div class="card stat blue"><div class="num"><?php echo $sent; ?></div><div class="label">Ambulance Sent</div></div><div class="card stat ok"><div class="num"><?php echo $available; ?></div><div class="label">Available Fleet</div></div><div class="card stat"><div class="num"><?php echo $pending; ?></div><div class="label">Pending</div></div><div class="card stat"><div class="num"><?php echo $ai; ?></div><div class="label">AI Checked</div></div><div class="card stat"><div class="num"><?php echo $onway; ?></div><div class="label">On The Way</div></div><div class="card stat"><div class="num"><?php echo $resolved; ?></div><div class="label">Resolved</div></div></div>
<div class="split" style="margin-top:18px"><div class="card"><h2>Priority Incident Queue</h2><div class="table-wrap"><table><thead><tr><th>ID</th><th>Incident</th><th>Severity</th><th>AI</th><th>Status</th><th>Ambulance</th><th>Action</th></tr></thead><tbody><?php if($recent && $recent->num_rows): while($r=$recent->fetch_assoc()): ?><tr><td>#<?php echo (int)$r['id']; ?></td><td><strong><?php echo htmlspecialchars($r['title']); ?></strong><br><span class="mini"><?php echo htmlspecialchars($r['location']); ?> · Priority <?php echo (int)$r['priority_score']; ?>/100</span></td><td><?php echo sr_badge($r['severity']); ?></td><td><?php echo sr_badge($r['ai_verdict']); ?><br><span class="mini"><?php echo (int)$r['ai_score']; ?>/100</span></td><td><?php echo sr_badge($r['status']); ?></td><td><?php echo htmlspecialchars($r['ambulance_name'] ?? 'Not assigned'); ?></td><td><a class="btn small" href="report-details.php?id=<?php echo (int)$r['id']; ?>">Open</a></td></tr><?php endwhile; else: ?><tr><td colspan="7"><div class="empty-state">No incident yet. Submit one as citizen first.</div></td></tr><?php endif; ?></tbody></table></div></div><div class="card"><h2>Live Response Feed</h2><div class="timeline live-feed"><?php if($logs && $logs->num_rows): while($l=$logs->fetch_assoc()): ?><div class="timeline-item"><strong><?php echo htmlspecialchars($l['action']); ?></strong><br><span class="mini"><?php echo htmlspecialchars($l['note'] ?? ''); ?></span><br><span class="mini"><?php echo sr_time($l['created_at']); ?></span></div><?php endwhile; else: ?><div class="timeline-item"><strong>Waiting for incident</strong><br><span class="mini">Submit, analyze, verify and dispatch to fill this feed.</span></div><?php endif; ?></div></div></div>
<?php sr_page_end(); ?>
