<?php
require_once __DIR__ . "/../includes/auth-check.php"; require_once __DIR__ . "/../Config/db.php"; require_once __DIR__ . "/../includes/ui.php";
$userId=(int)$_SESSION['user_id'];
$total=sr_count($conn,"SELECT COUNT(*) total FROM reports WHERE user_id=$userId");
$active=sr_count($conn,"SELECT COUNT(*) total FROM reports WHERE user_id=$userId AND status IN ('Pending','Verified','Ambulance Sent')");
$sent=sr_count($conn,"SELECT COUNT(*) total FROM reports WHERE user_id=$userId AND status='Ambulance Sent'");
$resolved=sr_count($conn,"SELECT COUNT(*) total FROM reports WHERE user_id=$userId AND status='Resolved'");
$recent=$conn->query("SELECT r.*, a.ambulance_name FROM reports r LEFT JOIN ambulance_locations a ON a.id=r.assigned_ambulance_id WHERE r.user_id=$userId ORDER BY r.created_at DESC LIMIT 6");
sr_page_start('Citizen Emergency Portal','dashboard');
?>
<div class="hero-card"><span class="demo-chip">Citizen side</span><h2>Report accident and track ambulance response</h2><p>Submit a road emergency with GPS, severity, people injured and evidence. After admin verification, the ambulance movement appears on the live map.</p><div class="toolbar" style="margin-top:18px"><a class="btn danger" href="submit-report.php">🚨 Submit Accident</a><a class="btn light" href="my-reports.php">My Reports</a><a class="btn light" href="map.php">Open Live Map</a></div></div>
<div class="grid grid-4" style="margin-top:18px"><div class="card stat"><div class="num"><?php echo $total; ?></div><div class="label">My Reports</div></div><div class="card stat danger"><div class="num"><?php echo $active; ?></div><div class="label">Active Cases</div></div><div class="card stat blue"><div class="num"><?php echo $sent; ?></div><div class="label">Ambulance Sent</div></div><div class="card stat ok"><div class="num"><?php echo $resolved; ?></div><div class="label">Resolved</div></div></div>
<div class="split" style="margin-top:18px"><div class="card"><h2>My Latest Emergency Reports</h2><div class="table-wrap"><table><thead><tr><th>ID</th><th>Incident</th><th>Priority</th><th>Status</th><th>Ambulance</th><th>Action</th></tr></thead><tbody><?php if($recent && $recent->num_rows): while($r=$recent->fetch_assoc()): ?><tr><td>#<?php echo (int)$r['id']; ?></td><td><strong><?php echo htmlspecialchars($r['title']); ?></strong><br><span class="mini"><?php echo htmlspecialchars($r['location']); ?></span></td><td><?php echo (int)$r['priority_score']; ?>/100</td><td><?php echo sr_badge($r['status']); ?></td><td><?php echo htmlspecialchars($r['ambulance_name'] ?? 'Not assigned'); ?></td><td><a class="btn small" href="report-details.php?id=<?php echo (int)$r['id']; ?>">View</a></td></tr><?php endwhile; else: ?><tr><td colspan="6"><div class="empty-state">No report yet. Submit one demo accident first.</div></td></tr><?php endif; ?></tbody></table></div></div><div class="card"><h2>Presentation Flow</h2><div class="timeline"><div class="timeline-item"><strong>1. Citizen submits emergency</strong><br><span class="mini">Use auto-fill for a perfect GPS demo.</span></div><div class="timeline-item"><strong>2. Admin runs AI triage</strong><br><span class="mini">AI score and evidence reason are generated.</span></div><div class="timeline-item"><strong>3. Admin dispatches ambulance</strong><br><span class="mini">Nearest available ambulance is locked.</span></div><div class="timeline-item"><strong>4. Map shows movement</strong><br><span class="mini">Ambulance arrives and timeline updates.</span></div></div></div></div>
<?php sr_page_end(); ?>
