<?php
require_once __DIR__ . "/../includes/auth-check.php"; require_once __DIR__ . "/../Config/db.php"; require_once __DIR__ . "/../includes/ui.php";
$id=(int)($_GET['id']??0); $uid=(int)$_SESSION['user_id']; $isAdmin=($_SESSION['role']??'')==='admin';
$stmt=$conn->prepare("SELECT r.*, u.name reporter_name, a.ambulance_name, a.driver_name, a.phone ambulance_phone, a.status ambulance_status FROM reports r LEFT JOIN users u ON u.id=r.user_id LEFT JOIN ambulance_locations a ON a.id=r.assigned_ambulance_id WHERE r.id=? LIMIT 1"); $stmt->bind_param('i',$id); $stmt->execute(); $r=$stmt->get_result()->fetch_assoc();
if(!$r || (!$isAdmin && (int)$r['user_id']!==$uid)){ $_SESSION['error']='Report not found or access denied.'; header('Location: '.($isAdmin?'admin-reports.php':'my-reports.php')); exit(); }
$logs=$conn->query("SELECT l.*, a.ambulance_name FROM response_logs l LEFT JOIN ambulance_locations a ON a.id=l.ambulance_id WHERE l.report_id=$id ORDER BY l.created_at ASC");
sr_page_start('Incident #'.$id,'reports');
?>
<div class="hero-card"><span class="demo-chip">Incident timeline</span><h2><?php echo htmlspecialchars($r['title']); ?></h2><p><?php echo htmlspecialchars($r['location']); ?> · <?php echo htmlspecialchars($r['severity']); ?> severity · Priority <?php echo (int)$r['priority_score']; ?>/100</p><div class="toolbar" style="margin-top:18px"><a class="btn light" href="<?php echo $isAdmin?'admin-reports.php':'my-reports.php'; ?>">Back</a><a class="btn light" href="map.php">Open Map</a><?php if($isAdmin): ?><form action="../actions/ai-video-check.php" method="POST"><input type="hidden" name="report_id" value="<?php echo $id; ?>"><button class="btn" type="submit">🤖 Analyze</button></form><?php if(($r['status']??'')==='Verified'): ?><form action="../actions/dispatch-ambulance.php" method="POST"><input type="hidden" name="report_id" value="<?php echo $id; ?>"><button class="btn danger" type="submit">🚑 Dispatch</button></form><?php else: ?><button class="btn light" type="button" disabled title="Verify before dispatch">🚑 Dispatch</button><?php endif; ?><?php endif; ?></div></div>
<div class="grid grid-4" style="margin-top:18px"><div class="card stat danger"><div class="num"><?php echo (int)$r['priority_score']; ?></div><div class="label">Priority Score</div></div><div class="card stat blue"><div class="num"><?php echo (int)$r['ai_score']; ?></div><div class="label">AI Score</div></div><div class="card stat"><div class="num"><?php echo (int)$r['people_injured']; ?></div><div class="label">People Injured</div></div><div class="card stat ok"><div class="num"><?php echo $r['ambulance_eta_minutes'] ? (int)$r['ambulance_eta_minutes'] : '—'; ?></div><div class="label">ETA Minutes</div></div></div>
<div class="split" style="margin-top:18px"><div class="card"><h2>Incident Information</h2><div class="grid grid-2"><p><strong>Status</strong><br><?php echo sr_badge($r['status']); ?></p><p><strong>AI Verdict</strong><br><?php echo sr_badge($r['ai_verdict']); ?></p><p><strong>Road / Area</strong><br><?php echo htmlspecialchars($r['road_name'] ?: 'N/A'); ?></p><p><strong>Landmark</strong><br><?php echo htmlspecialchars($r['nearest_landmark'] ?: 'N/A'); ?></p><p><strong>Vehicles</strong><br><?php echo htmlspecialchars($r['vehicles_involved'] ?: 'N/A'); ?></p><p><strong>GPS</strong><br><?php echo htmlspecialchars(($r['latitude'] ?: 'N/A').' , '.($r['longitude'] ?: 'N/A')); ?></p></div><h3>Description</h3><p class="mini" style="font-size:14px;color:var(--soft)"><?php echo nl2br(htmlspecialchars($r['description'])); ?></p><h3>AI Reason</h3><div class="ai-panel"><div class="ai-step"><span>Evidence confidence</span><strong><?php echo (int)$r['ai_score']; ?>/100</strong></div><div class="progress"><span style="width:<?php echo (int)$r['ai_score']; ?>%"></span></div><p class="mini"><?php echo htmlspecialchars($r['ai_reason'] ?: 'AI triage is not run yet.'); ?></p></div></div><div class="card"><h2>Ambulance + Timeline</h2><p><strong>Assigned Ambulance</strong><br><?php echo htmlspecialchars($r['ambulance_name'] ?: 'Not assigned'); ?></p><p class="mini"><?php echo htmlspecialchars(($r['driver_name'] ?: '').' '.($r['ambulance_phone'] ?: '')); ?></p><div class="timeline"><?php if($logs && $logs->num_rows): while($l=$logs->fetch_assoc()): ?><div class="timeline-item"><strong><?php echo htmlspecialchars($l['action']); ?></strong><br><span class="mini"><?php echo htmlspecialchars($l['note'] ?: ''); ?></span><br><span class="mini"><?php echo sr_time($l['created_at']); ?></span></div><?php endwhile; else: ?><div class="timeline-item"><strong>Report created</strong><br><span class="mini">No response log yet.</span></div><?php endif; ?></div></div></div>
<?php sr_page_end(); ?>
